// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar for jlab-flutter-development-kit
  jlabSidebar: [
    // Introduction - the main page
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },

    // API Management Category
    {
      type: 'category',
      label: 'API Management',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'API Management',
        description: 'Manage APIs, endpoints, and OpenAPI specifications',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-management',
        },
      ],
    },

    // Feature Development Category
    {
      type: 'category',
      label: 'Feature Development',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Feature Development',
        description: 'Create features and pages for your Flutter app',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'feature-development',
        },
      ],
    },

    // Setup Category
    {
      type: 'category',
      label: 'Setup',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Setup',
        description: 'Setup flavors, Firebase, PowerSync, CI/CD, and more',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'setup',
        },
      ],
    },

    // Project Category
    {
      type: 'category',
      label: 'Project',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Project Management',
        description: 'Initialize, create, and manage projects',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'project',
        },
      ],
    },

    // Concepts Category
    {
      type: 'category',
      label: 'Concepts',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Concepts',
        description: 'Understanding concepts and architecture',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts',
        },
      ],
    },

    // Mason Bricks Category
    {
      type: 'category',
      label: 'Mason Bricks',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Mason Bricks',
        description: 'Create, modify, and test Mason bricks',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'bricks',
        },
      ],
    },
  ],
};

module.exports = sidebars;
