// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar for jlab-flutter-development-kit
  jlabSidebar: [
    // Introduction - the main page
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description: 'Learn how to set up and use jlab-flutter-development-kit',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'How-To Guides',
        description: 'Practical guides for common tasks',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'howto',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Command Reference',
        description: 'Detailed command documentation',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'Explanations',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Explanations',
        description: 'Understanding concepts and architecture',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'explanation',
        },
      ],
    },
  ],
};

module.exports = sidebars;
